algoritmo "Estruturas condicionais"
// Função :
// Autor :
// Data : 03/11/2022
// Seção de Declarações 
var
nota1, nota2, nota3, media: real
inicio
Escreval ("Informe a nota 1")
leia (nota1)
Escreval ("Informe a nota 2")
leia (nota2)
Escreval ("Informe a nota 3")
leia (nota3)
media <- (nota1+nota2+nota3)/3

se media <7 entao
Escreval ("Vocè está de recuperação! Estude e boa sorte!")
senao
Escreval ("Você passou! Parabéns!")
fimse
fimalgoritmo
